addEventHandler("onResourceStart", resourceRoot, function()
   local numberpickPed = createPed(numberpickPedTable[1],numberpickPedTable[2],numberpickPedTable[3],numberpickPedTable[4])
   setElementData(numberpickPed, "ped:name", "Alisson")
   setElementData(numberpickPed, "ped:prefix", "Számfejtő")
   setElementData(numberpickPed, "numberpick:ped", true)
   setElementRotation(numberpickPed,-0,0, 231.7933807373)
   setElementInterior(numberpickPed, numberpickPedTable[5])
   setElementDimension(numberpickPed, numberpickPedTable[6])
   setElementFrozen(numberpickPed, true)
end)
